POST http://localhost:8080/v1/auth/login 
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password"
}

###

GET http://localhost:8080/v1/categories
Content-Type: application/json
Authorization: Bearer 